import { type InferSelectModel } from 'drizzle-orm';
import * as schema from '~/database/schema';

export type Product = InferSelectModel<typeof schema.products>;
export type Plan = InferSelectModel<typeof schema.plans>;
export type AddOn = InferSelectModel<typeof schema.addOns>;

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Cloud Hosting',
    isAddOn: false,
    tenantId: 't1',
    description: 'Scalable cloud infrastructure',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 'p2',
    name: 'Enterprise CRM',
    isAddOn: false,
    tenantId: 't1',
    description: 'Advanced customer relationship management',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
];

export const INITIAL_PLANS: Plan[] = [
  // Plans for Product 1 (Cloud Hosting)
  {
    id: 'pl1',
    productId: 'p1',
    name: 'Standard Monthly',
    price: '99',
    planType: 'TierBased',
    billingCycle: 'monthly',
    isRecurring: true,
    currency: 'usd',
    description: 'Perfect for small teams',
    prevPlanId: null,
    credits: null,
    metadata: null,
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 'pl2',
    productId: 'p1',
    name: 'Premium Annual',
    price: '990',
    planType: 'TierBased',
    billingCycle: 'annual',
    isRecurring: true,
    currency: 'usd',
    description: 'Best value for growing startups',
    prevPlanId: null,
    credits: null,
    metadata: null,
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 'pl3',
    productId: 'p1',
    name: 'Enterprise Plus',
    price: '299',
    planType: 'TierBased',
    billingCycle: 'monthly',
    isRecurring: true,
    currency: 'usd',
    description: 'Dedicated resources and high availability',
    prevPlanId: null,
    credits: null,
    metadata: null,
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  // Plans for Product 2 (Enterprise CRM)
  {
    id: 'pl4',
    productId: 'p2',
    name: 'CRM Starter',
    price: '49',
    planType: 'TierBased',
    billingCycle: 'monthly',
    isRecurring: true,
    currency: 'usd',
    description: 'Essential CRM features',
    prevPlanId: null,
    credits: null,
    metadata: null,
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 'pl5',
    productId: 'p2',
    name: 'CRM Professional',
    price: '149',
    planType: 'TierBased',
    billingCycle: 'monthly',
    isRecurring: true,
    currency: 'usd',
    description: 'Full sales automation Suite',
    prevPlanId: null,
    credits: null,
    metadata: null,
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 'pl6',
    productId: 'p2',
    name: 'CRM Elite Annual',
    price: '1490',
    planType: 'TierBased',
    billingCycle: 'annual',
    isRecurring: true,
    currency: 'usd',
    description: 'Premium support and unlimited records',
    prevPlanId: null,
    credits: null,
    metadata: null,
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
];

export const INITIAL_ADDONS: AddOn[] = [
  // Add-ons for Product 1
  {
    id: 'a1',
    productId: 'p1',
    name: 'Managed Backups',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 'a2',
    productId: 'p1',
    name: 'Global CDN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  // Add-ons for Product 2
  {
    id: 'a3',
    productId: 'p2',
    name: '24/7 Priority Support',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 'a4',
    productId: 'p2',
    name: 'Advanced Analytics',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  },
];

export const ADDON_PRICES: Record<string, number> = {
  a1: 20,
  a2: 15,
  a3: 50,
  a4: 35,
};
